name: supernova_flutter_ui_toolkit
description: Set of extensions for Flutter SDK.
version: 0.0.1
author: Supernova.io <support@supernova.io>
homepage: https://github.com/Supernova-Studio/flutter-ui-toolkit

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

